// <auto-generated />
using System;
using EventManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManagement.Persistence.Migrations
{
    [DbContext(typeof(EventManagementDbContext))]
    [Migration("20221018142708_EventAndIntegrationServiceData")]
    partial class EventAndIntegrationServiceData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EventManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Müzik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sinema"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Eğlence"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aile"
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 2,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Konya"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kocaeli"
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Events.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ApprovedForListing")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ParticipantLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Event");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address",
                            ApplicationDeadline = new DateTime(2022, 10, 23, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5328),
                            ApprovedForListing = true,
                            CategoryId = 3,
                            CityId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget nulla nibh. Donec tempus ex quis egestas lacinia. Donec aliquam ultricies massa, at sagittis massa porta vel. Fusce porta augue sed scelerisque placerat. Donec sodales, orci non vulputate ultrices, libero magna tempor dui, commodo ultrices magna nunc ut sapien. Vivamus sollicitudin commodo vehicula. Pellentesque sit amet vivamus.",
                            Discriminator = "Event",
                            Name = "Gwendolin Ankara Spor",
                            ParticipantLimit = 1,
                            Start = new DateTime(2022, 10, 24, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5311),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address",
                            ApplicationDeadline = new DateTime(2022, 10, 18, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5330),
                            ApprovedForListing = true,
                            CategoryId = 1,
                            CityId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget nulla nibh. Donec tempus ex quis egestas lacinia. Donec aliquam ultricies massa, at sagittis massa porta vel. Fusce porta augue sed scelerisque placerat. Donec sodales, orci non vulputate ultrices, libero magna tempor dui, commodo ultrices magna nunc ut sapien. Vivamus sollicitudin commodo vehicula. Pellentesque sit amet vivamus.",
                            Discriminator = "Event",
                            Name = "John İstanbul Müzik",
                            ParticipantLimit = 2,
                            Start = new DateTime(2022, 10, 19, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5329),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Events.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.IntegrationService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WebDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("IntegrationServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Google",
                            Email = "iss@iss.com",
                            PasswordHash = "$2a$11$07EUmoZxDMyAeIamjR8aeui2M.WKzZ7NfgHLQVu.ryB8ZkBn3YABK",
                            WebDomain = "https://www.google.com.tr/"
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$LTwig7Q1qvqrGCsBES3YaeUJ4/NPdyUOvgIwVu/TNyfVGuL9DPOHW"
                        },
                        new
                        {
                            Id = 2,
                            Email = "gwendolyn.connelly@ethereal.email",
                            FirstName = "Gwendolin",
                            LastName = "Connely",
                            PasswordHash = "$2a$11$GZnQc1ePrcdTGa4sSfpsFeZEIjdxMFMPtuSI5UAN89PvFxJrHv9w."
                        },
                        new
                        {
                            Id = 3,
                            Email = "john.doe@admin.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$uyjFi3yqEJiFpZu4IkCxfOmjL.EKPQEu4pobskKZKM3UU3xYDkwyO"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jane.doe@admin.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$uyjFi3yqEJiFpZu4IkCxfOmjL.EKPQEu4pobskKZKM3UU3xYDkwyO"
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Users.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Events.TicketEvent", b =>
                {
                    b.HasBaseType("EventManagement.Domain.Entities.Events.Event");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.HasDiscriminator().HasValue("TicketEvent");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Address = "Address",
                            ApplicationDeadline = new DateTime(2022, 10, 17, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5350),
                            ApprovedForListing = true,
                            CategoryId = 1,
                            CityId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget nulla nibh. Donec tempus ex quis egestas lacinia. Donec aliquam ultricies massa, at sagittis massa porta vel. Fusce porta augue sed scelerisque placerat. Donec sodales, orci non vulputate ultrices, libero magna tempor dui, commodo ultrices magna nunc ut sapien. Vivamus sollicitudin commodo vehicula. Pellentesque sit amet vivamus.",
                            Discriminator = "TicketEvent",
                            Name = "Gwendolin Eskişehir Müzik",
                            ParticipantLimit = 1,
                            Start = new DateTime(2022, 10, 17, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5349),
                            UserId = 2,
                            Price = 109.00m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address",
                            ApplicationDeadline = new DateTime(2022, 10, 28, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5355),
                            ApprovedForListing = false,
                            CategoryId = 1,
                            CityId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget nulla nibh. Donec tempus ex quis egestas lacinia. Donec aliquam ultricies massa, at sagittis massa porta vel. Fusce porta augue sed scelerisque placerat. Donec sodales, orci non vulputate ultrices, libero magna tempor dui, commodo ultrices magna nunc ut sapien. Vivamus sollicitudin commodo vehicula. Pellentesque sit amet vivamus.",
                            Discriminator = "TicketEvent",
                            Name = "Jane Konya Sinema",
                            ParticipantLimit = 1,
                            Start = new DateTime(2022, 10, 28, 17, 27, 7, 934, DateTimeKind.Local).AddTicks(5354),
                            UserId = 4,
                            Price = 999.99m
                        });
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Events.Event", b =>
                {
                    b.HasOne("EventManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Domain.Entities.Users.User", "User")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Events.EventParticipant", b =>
                {
                    b.HasOne("EventManagement.Domain.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventManagement.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Users.UserRole", b =>
                {
                    b.HasOne("EventManagement.Domain.Entities.Users.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManagement.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventManagement.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("CreatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
